spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:upright_mahjong.sqlite3
  main:
    banner-mode: off
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){magenta} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan} %clr([%X{userId}=>%X{traceId}]){blue} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    com.github.maojx0630: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml , classpath:/mapper/**/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    banner: false